[package]
name = "vol"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
clap = { version = "4.5.48", features = ["derive"] }
num-format = "0.4.4"
statrs = "0.18.0"
tabled = { version = "0.20.0" }
tokio-test = "0.4.4"
yahoo_finance_api = "4.1.0"
